PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `User` (`Id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `Name` TEXT NOT NULL, `Surname` TEXT NOT NULL, `Email` TEXT NOT NULL, `Password` TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "Ingredients" (
    IdIngredients INTEGER PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL
);
CREATE TABLE `Proteins` (`IdProteins` INTEGER PRIMARY KEY NOT NULL, `Name` TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS "ContainProteins" (
    IdPoke INTEGER NOT NULL REFERENCES "Poke"(IdPoke),
    IdProteins INTEGER NOT NULL REFERENCES "Proteins"(IdProteins),
    PRIMARY KEY (IdPoke, IdProteins)
);
CREATE TABLE IF NOT EXISTS "ContainIngredients" (
    IdPoke INTEGER NOT NULL REFERENCES "Poke"(IdPoke),
    IdIngredients INTEGER NOT NULL REFERENCES "Ingredients"(IdIngredients),
    Quantity INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (IdPoke, IdIngredients)
);
CREATE TABLE IF NOT EXISTS "Order" (`IdOrder` INTEGER PRIMARY KEY NOT NULL, `Data` TEXT, `IdUser` INTEGER NOT NULL REFERENCES `User`(`Id`), `Price` NUMERIC NOT NULL);
CREATE TABLE Poke (
    IdPoke INTEGER PRIMARY KEY NOT NULL,
    Size TEXT NOT NULL DEFAULT 'R',
    Base TEXT NOT NULL DEFAULT 'Riso bianco',
    Price NUMERIC NOT NULL,
    IdOrder INTEGER NOT NULL REFERENCES "Order"(IdOrder),
    Quantity INTEGER NOT NULL DEFAULT 1
);
DELETE FROM sqlite_sequence;
COMMIT;
